commom: &commom
  adapter: postgresql
  encoding: utf8
  username: postgres

development:
  <<: *commom
  database: sirvame_development

test:
  <<: *commom
  database: sirvame_test

production:
  <<: *commom
  database: sirvame_production