commom: &commom
  adapter: postgresql
  encoding: utf8
  username: postgres

development:
  <<: *commom
  database: sirvame_development
  password: 123qwe

test:
  <<: *commom
  database: sirvame_test
  password: 123qwe

production:
  <<: *commom
  database: sirvame_production
  password: expira90
